// react-basics/src/day03/vue/PropertyForm.vue
<script setup lang="ts">
import { reactive } from 'vue'
import { CATEGORY_LABEL, type Category } from '../../day02/types'
import type { PropertyInput } from '../api'

defineProps<{
  pending: boolean
  errorMessage?: string
}>()

const emit = defineEmits<{
  submit: [input: PropertyInput, reset: () => void]
}>()

const initialForm = (): PropertyInput => ({
  title: '',
  category: 'apartment',
  deposit: 0,
  monthlyRent: 0,
  area: 0,
  description: '',
})

const form = reactive(initialForm())

function reset() {
  Object.assign(form, initialForm())
}

function onSubmit() {
  if (!form.title.trim()) return
  emit('submit', { ...form, title: form.title.trim() }, reset)
}
</script>

<template>
  <form @submit.prevent="onSubmit">
    <h2>매물 등록</h2>
    <input v-model="form.title" placeholder="매물명" />
    <select v-model="form.category">
      <option
        v-for="(label, key) in CATEGORY_LABEL"
        :key="key"
        :value="key as Category"
      >
        {{ label }}
      </option>
    </select>
    <input v-model.number="form.deposit" type="number" placeholder="보증금" />
    <input v-model.number="form.monthlyRent" type="number" placeholder="월세" />
    <input v-model.number="form.area" type="number" placeholder="면적" />
    <textarea v-model="form.description" placeholder="설명" />
    <button type="submit" :disabled="pending">
      {{ pending ? '등록 중...' : '등록' }}
    </button>
    <p v-if="errorMessage">{{ errorMessage }}</p>
  </form>
</template>

// react-basics/src/day03/react/PropertyForm.tsx
import React, { useState } from "react";
import { CATEGORY_LABEL, type Category } from "../../day02/types";
import type { PropertyInput } from "../api";

interface Props {
  pending: boolean;
  onSubmit: (input: PropertyInput, reset: () => void) => void;
  errorMessage?: string;
}

export const PropertyForm = ({
  pending,
  onSubmit,
  errorMessage = "",
}: Props) => {
  const initialForm = (): PropertyInput => {
    return {
      title: "",
      category: "apartment",
      deposit: 0,
      monthlyRent: 0,
      area: 0,
      description: "",
    };
  };

  const [form, setForm] = useState<PropertyInput>(initialForm());

  const reset = () => {
    setForm(initialForm());
  };

  const submitFn = (event: React.SubmitEvent) => {
    event.preventDefault();
    if (!form.title.trim()) return;
    onSubmit({ ...form, title: form.title.trim() }, reset);
  };

  return (
    <form onSubmit={submitFn}>
      <h2>매물 등록</h2>
      <input
        value={form.title}
        onChange={(e) => setForm({ ...form, title: e.target.value })}
        placeholder="매물명"
      />

      <select
        onChange={(e) =>
          setForm({ ...form, category: e.target.value as Category })
        }
      >
        {
          // 객체 반복문 이렇게 맞나?
          Object.entries(CATEGORY_LABEL).map((entry) => (
            <option key={entry[0]} value={entry[0] as Category}>
              {entry[1]}
            </option>
          ))
        }
      </select>

      <input
        type="number"
        value={form.deposit}
        onChange={(e) => setForm({ ...form, deposit: Number(e.target.value) })}
        placeholder="보증금"
      />
      <input
        type="number"
        value={form.monthlyRent}
        onChange={(e) =>
          setForm({ ...form, monthlyRent: Number(e.target.value) })
        }
        placeholder="월세"
      />
      <input
        type="number"
        value={form.area}
        onChange={(e) => setForm({ ...form, area: Number(e.target.value) })}
        placeholder="면적"
      />
      <textarea
        value={form.description}
        onChange={(e) => setForm({ ...form, description: e.target.value })}
        placeholder="설명"
      />

      <button type="submit" disabled={pending}>
        {pending ? "등록 중..." : "등록"}
      </button>
      {errorMessage && <p>{errorMessage}</p>}
    </form>
  );
};
