// react-basics/src/day02/React/CategoryFilter.tsx
import { CATEGORY_LABEL, type Category } from "../types";

export const CategoryFilter = (
  selected: Category | "all",
  onChange: (category: Category | "all") => void,
) => {
  const options = [
    { value: "all", label: "전체" },
    ...(Object.keys(CATEGORY_LABEL) as Category[]).map((key) => ({
      value: key,
      label: CATEGORY_LABEL[key],
    })),
  ] as { value: Category | "all"; label: string }[];

  return (
    <>
      {options.map((option) => (
        <button
          type="button"
          key={option.value}
          onClick={() => onChange(option.value)}
          className={selected === option.value ? "selected" : ""}
        >
          {option.label}
        </button>
      ))}
    </>
  );
};

// react-basics/src/day02/vue/CategoryFilter.vue
<script setup lang="ts">
import { CATEGORY_LABEL, type Category } from '../types'

defineProps<{
  selected: Category | 'all'
}>()

const emit = defineEmits<{
  change: [value: Category | 'all']
}>()

const options = [
  { value: 'all', label: '전체' },
  ...(Object.keys(CATEGORY_LABEL) as Category[]).map((key) => ({
    value: key,
    label: CATEGORY_LABEL[key],
  })),
] as { value: Category | 'all'; label: string }[]
</script>

<template>
  <div>
    <button
      v-for="option in options"
      :key="option.value"
      type="button"
      :class="{ active: selected === option.value }"
      @click="emit('change', option.value)"
    >
      {{ option.label }}
    </button>
  </div>
</template>
