// react-basics/src/day02/vue/PropertyApp.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import SearchInput from './SearchInput.vue'
import CategoryFilter from './CategoryFilter.vue'
import ItemList from './ItemList.vue'
import ItemDetail from './ItemDetail.vue'
import { useEscapeKey } from './useEscapeKey'
import { properties } from '../data'
import type { Category } from '../types'

const keyword = ref('')
const category = ref<Category | 'all'>('all')
const selectedId = ref<number | null>(null)

const filteredItems = computed(() => {
  const q = keyword.value.trim()
  return properties.filter(
    (p) =>
      (category.value === 'all' || p.category === category.value) &&
      p.title.includes(q),
  )
})

const selectedItem = computed(
  () => properties.find((p) => p.id === selectedId.value) ?? null,
)

// 카테고리가 바뀌면 선택 해제
watch(category, () => {
  selectedId.value = null
})

// ESC로 상세 닫기
useEscapeKey(() => {
  selectedId.value = null
})
</script>

<template>
  <div>
    <h1>매물 검색</h1>

    <SearchInput v-model="keyword" />
    <CategoryFilter :selected="category" @change="category = $event" />

    <p>{{ filteredItems.length }}건</p>

    <ItemList
      :items="filteredItems"
      :selected-id="selectedId"
      @select="selectedId = $event"
    />

    <ItemDetail v-if="selectedItem" :item="selectedItem">
      <button type="button" @click="selectedId = null">닫기</button>
    </ItemDetail>
    <p v-else>매물을 선택하세요</p>
  </div>
</template>

// react-basics/src/day02/React/PropertyApp.tsx
import { useState } from "react";
import type { Category } from "../types";
import { properties } from "../data";
import { useEscapeKey } from "./useEscapeKey";
import { SearchInput } from "./SearchInput";
import { CategoryFilter } from "./CategoryFilter";
import { ItemList } from "./ItemList";
import { ItemDetail } from "./ItemDetail";

export const PropertyApp = () => {
  const [keyword, setKeyword] = useState("");
  const [category, setCategory] = useState<Category | "all">("all");
  const [selectedId, setSelectedId] = useState<number | null>(null);

  const filteredItems = properties.filter(
    (p) =>
      (category === "all" || p.category === category) &&
      p.title.includes(keyword.trim()),
  );

  const selectedItem = properties.find((p) => p.id === selectedId) ?? null;

  const selectCategory = (cate: Category | "all") => {
    setCategory(cate);
    setSelectedId(null);
  };

  useEscapeKey(() => {
    setSelectedId(null);
  });

  return (
    <>
      <h1>매물 검색</h1>

      <SearchInput value={keyword} onChange={setKeyword} />
      <CategoryFilter selected={category} onChange={selectCategory} />

      <p>{filteredItems.length}건</p>

      <ItemList
        items={filteredItems}
        selectedId={selectedId}
        onSelect={setSelectedId}
      />

      {/* v-if / v-else → 삼항 연산자 */}
      {selectedItem ? (
        <ItemDetail item={selectedItem}>
          <button type="button" onClick={() => setSelectedId(null)}>
            닫기
          </button>
        </ItemDetail>
      ) : (
        <p>매물을 선택하세요</p>
      )}
    </>
  );
};
